import React from "react";
import Head from "next/head";
import { Hero } from "../components/hero";
import { NavigationFrontpage } from "../components/navigationFrontpage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lukas und Lukas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Hero />
        <NavigationFrontpage />
      </div>
    </div>
  );
}
